int setup_client_connection(char *host_arg, char *port_arg);
void wait_for_thread(int sockfd);
int login(int sockfd);
void print_login_page();
void read_login_input(char *buffer);
void core_loop(int sockfd);
int select_client_action(int sockfd);
void play_minesweeper(int sockfd);
void update_game_state(GameState *game, int sockfd);
char select_game_action();
void get_and_send_tile_coordinates(int sockfd);
void print_response_output(int response, int sockfd);
void show_leaderboard();
void print_leaderboard_contents(int response, int sockfd);
void clear_buffer();