#define MAX_READ_LENGTH 20
#define BACKLOG 50

#define NORMAL 1
#define GAME_LOST 2
#define GAME_WON 3
#define NO_MINE_AT_FLAG 4
#define TILE_ALREADY_REVEALED 5
#define INVALID_COORDINATES 6

#define HIGHSCORES_EMPTY 11
#define HIGHSCORES_PRESENT 12
#define HIGHSCORES_END 13